export const techSpecs = {
	purifiers: [
		{
			title: 'Winix Zero Pro',
			img:
				'https://winixeurope.eu/wp-content/uploads/2019/01/Winix-Zero-Pro-2.png',
			modelNo: 'AZPU373-IWB',
			maxRoomCapacity: '120 m2',
			maxAirFlow: '470 m3/h',
			powerConsumption: '5-90 Watt',
			noiseLevel: '28-55 dB',
			dimensions: '415 x 245 x 600 mm',
			weight: '8.5kg',
			filterReplacement: 'Yes',
			airQualityLight: 'Blue / Green / Amber / Red',
			dustSensor: 'Yes',
			odourSensor: 'Yes',
			fanSpeeds: '4',
			sleepMode: 'Yes',
			autoMode: 'Yes',
			timer: 'Yes',
			bluetoothSpeaker: 'No',
			plasmawave: 'Yes',
		},
		{
			title: 'Winix Zero-N',
			img:
				'https://winixeurope.eu/wp-content/uploads/2019/07/ZERO-N_Front_Grey-compressed.png',
			modelNo: 'AZNU230-HWB',
			maxRoomCapacity: '45 m2',
			maxAirFlow: '330 m3/h',
			powerConsumption: '3-40 Watt',
			noiseLevel: '26-47 dB',
			dimensions: '350 x 207 x 470 mm',
			weight: '6,2 kg',
			filterReplacement: 'Yes',
			airQualityLight: 'Blue /  Amber / Red',
			dustSensor: 'Yes',
			odourSensor: 'No',
			fanSpeeds: '3',
			sleepMode: 'Yes',
			autoMode: 'Yes',
			timer: 'No',
			bluetoothSpeaker: 'No',
			plasmawave: 'No',
		},
		{
			title: 'Winix Zero',
			img:
				'https://winixeurope.eu/wp-content/uploads/2019/05/ECARF-Certified-air-purifier.png',
			modelNo: 'AZBU330-HWB',
			maxRoomCapacity: '99 m2',
			maxAirFlow: '390 m3/h',
			powerConsumption: '3-70 Watt',
			noiseLevel: '27-51 dB',
			dimensions: '380 x 208 x 600 mm',
			weight: '7 kg',
			filterReplacement: 'Yes',
			airQualityLight: 'Blue /  Amber / Red',
			dustSensor: 'Yes',
			odourSensor: 'No',
			fanSpeeds: '4',
			sleepMode: 'Yes',
			autoMode: 'Yes',
			timer: 'Yes',
			bluetoothSpeaker: 'No',
			plasmawave: 'Yes',
		},
	],
	humidifiers: [
		{
			title: 'Atmos Speaker Humidifier',
			img:
				'https://secure.img1-fg.wfcdn.com/im/26361049/resize-h800-w800%5Ecompr-r85/7104/71047670/Atmos+Speaker+Humidifier.jpg',
			material: 'Plastic',
			wheels: 'No',
			filterNeeded: 'No',
			power: 'Eletric',
			remoteControl: 'No',
			timer: 'Yes',
			autoShutOff: 'Yes',
			portable: 'Yes',
			roomSize: '107sqm',
			assemblyNeeded: 'No',
		},
		{
			title: 'Boneco U300 Ultrasonic Humidifier',
			img:
				'https://www.robertdyas.co.uk/media/catalog/product/cache/ee7f57371963fdaf9f4353c1acf7bd18/2/0/205256.jpg',
			material: 'Plastic',
			wheels: 'No',
			filterNeeded: 'No',
			power: 'Eletric',
			capacity: '5L',
			noiseLevel: '<35 dB(A)',
			dimensions: '308 x 165 x 325 mm',
			assemblyNeeded: 'No',
			maxRoomSize: '125 m3',
			weight: '2.74kg',
		},
	],
	fans: [
		{
			title: 'Boneco F100 Desk Fan',
			id: 101,
			voltage: '220 – 240V ~ 50Hz',
			airSpeed: '4.1 m/sec',
			blade: '150 mm',
			powerConsumption: '20 W (max. level)',
			dimensions: '202 x 207 x 238 mm',
			noiseLevel: '32 – 55 dB(A)',
			airflow: '610 m³/h',
			weight: '1.6 kg',
		},
		{
			title: 'Boneco F120 Air Shower',
			id: 102,
			voltage: '220 – 240V ~ 50Hz',
			airSpeed: '4.1 m/sec',
			blade: '150 mm',
			powerConsumption: '20 W (max. level)',
			dimensions: '278 x 278 x 540 mm',
			noiseLevel: '32 – 55 dB(A)',
			airflow: '610 m³/h',
			weight: '2.9 kg',
		},
		{
			title: 'Boneco F220 Air Shower',
			id: 103,
			voltage: '220 – 240V ~ 50Hz',
			airSpeed: '3.9 m/sec',
			blade: '225 mm',
			powerConsumption: '33 W (max. level)',
			dimensions: '375 x 375 x 850 mm',
			noiseLevel: '35 – 58 dB(A)',
			airflow: '1260 m³/h',
			weight: '6.7 kg',
		},
		{
			title: 'Boneco F230 Air Shower',
			id: 104,
			voltage: '220 – 240V ~ 50Hz',
			airSpeed: '3.9 m/sec',
			blade: '225 mm',
			powerConsumption: '33 W (max. level)',
			dimensions: '375 x 375 x 1210 mm',
			noiseLevel: '35 – 58 dB(A)',
			airflow: '1260 m³/h',
			weight: '8.9 kg',
		},
	],
};
